import Header from "@/components/Header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ManagedUI, ManagedUIProvider } from "@/contexts/Modal";
import { StoreAuthProvider } from "@/hooks/useAuth";
import Container from "@/components/Container/Container";
import { useContainer } from "@/contexts/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ManagedUIProvider>
          <StoreAuthProvider>
            <Header />
            {children}
          </StoreAuthProvider>
        </ManagedUIProvider>
      </body>
    </html>
  );
}
